// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'academic_calendar.freezed.dart';
part 'academic_calendar.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// A semester's academic calendar, flattened.
///
/// VTOP renders each month as a week grid, but the grid is a display concern:
/// the days are carried here as one date-ordered list, so the app can look up a
/// date, filter holidays, or lay out its own view.
@freezed
@meta.immutable
sealed class AcademicCalendar with _$AcademicCalendar {
  const AcademicCalendar._();
  const factory AcademicCalendar({
    required String semesterId,
    required String classGroupId,
    required List<CalendarMonthRef> months,
    required List<CalendarDay> days,
  }) = _AcademicCalendar;
  static Future<AcademicCalendar> default_() => RustLib.instance.api
      .crateApiVtopTypesAcademicCalendarAcademicCalendarDefault();

  factory AcademicCalendar.fromJson(Map<String, dynamic> json) =>
      _$AcademicCalendarFromJson(json);
}

/// A single dated day of the academic calendar.
@freezed
@meta.immutable
sealed class CalendarDay with _$CalendarDay {
  const factory CalendarDay({
    required String date,
    required int day,
    required String weekday,
    required List<CalendarEvent> events,
  }) = _CalendarDay;

  factory CalendarDay.fromJson(Map<String, dynamic> json) =>
      _$CalendarDayFromJson(json);
}

/// One entry on a calendar day.
@freezed
@meta.immutable
sealed class CalendarEvent with _$CalendarEvent {
  const factory CalendarEvent({
    required String description,
    required String label,
  }) = _CalendarEvent;

  factory CalendarEvent.fromJson(Map<String, dynamic> json) =>
      _$CalendarEventFromJson(json);
}

/// A month button on the calendar page.
@freezed
@meta.immutable
sealed class CalendarMonthRef with _$CalendarMonthRef {
  const factory CalendarMonthRef({
    required String label,
    required String calDate,
  }) = _CalendarMonthRef;

  factory CalendarMonthRef.fromJson(Map<String, dynamic> json) =>
      _$CalendarMonthRefFromJson(json);
}

/// A class group option, e.g. `COMB` "All Class Group (Combined)".
@freezed
@meta.immutable
sealed class ClassGroup with _$ClassGroup {
  const factory ClassGroup({required String id, required String name}) =
      _ClassGroup;

  factory ClassGroup.fromJson(Map<String, dynamic> json) =>
      _$ClassGroupFromJson(json);
}
