// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'capstone_attendance.freezed.dart';
part 'capstone_attendance.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Capstone/SDP attendance for one semester.
///
/// This is not per-course, so it does not fit [`super::attendance::AttendanceRecord`]:
/// there is no course code, faculty or slot, and the tally is
/// present/on-duty/absent rather than attended/total. VTOP returns the summary
/// and the day-by-day calendar in a single response, so both live here.
///
/// The sub-structs group the fields the way VTOP's three tables do, but they
/// are flattened on the wire: the app persists a capstone as one record, so a
/// flat JSON object is what the Dart side wants to read.
@freezed
@meta.immutable
sealed class CapstoneAttendance with _$CapstoneAttendance {
  const CapstoneAttendance._();
  const factory CapstoneAttendance({
    required CapstoneInfo info,
    required CapstoneSummary summary,
    required List<CapstonePunch> punches,
  }) = _CapstoneAttendance;
  static Future<CapstoneAttendance> default_() => RustLib.instance.api
      .crateApiVtopTypesCapstoneAttendanceCapstoneAttendanceDefault();

  factory CapstoneAttendance.fromJson(Map<String, dynamic> json) =>
      _$CapstoneAttendanceFromJson(json);
}

/// The registration details shown above the capstone attendance summary.
@freezed
@meta.immutable
sealed class CapstoneInfo with _$CapstoneInfo {
  const CapstoneInfo._();
  const factory CapstoneInfo({
    required String title,
    required String guideEvaluationStatus,
    required String dateOfRegistration,
  }) = _CapstoneInfo;
  static Future<CapstoneInfo> default_() => RustLib.instance.api
      .crateApiVtopTypesCapstoneAttendanceCapstoneInfoDefault();

  factory CapstoneInfo.fromJson(Map<String, dynamic> json) =>
      _$CapstoneInfoFromJson(json);
}

/// One day in the capstone attendance calendar.
@freezed
@meta.immutable
sealed class CapstonePunch with _$CapstonePunch {
  const factory CapstonePunch({
    required String serial,
    required String date,
    required String day,
    required String dayType,
    required String status,
    required String punchTime,
  }) = _CapstonePunch;

  factory CapstonePunch.fromJson(Map<String, dynamic> json) =>
      _$CapstonePunchFromJson(json);
}

/// The present / on-duty / absent tally for the capstone.
///
/// Deliberately not folded into attended/total the way a course is: a day
/// marked on duty is neither attended nor absent, and collapsing the three
/// counts loses that.
@freezed
@meta.immutable
sealed class CapstoneSummary with _$CapstoneSummary {
  const CapstoneSummary._();
  const factory CapstoneSummary({
    required String present,
    required String onDuty,
    required String absent,
    required String percentage,
  }) = _CapstoneSummary;
  static Future<CapstoneSummary> default_() => RustLib.instance.api
      .crateApiVtopTypesCapstoneAttendanceCapstoneSummaryDefault();

  factory CapstoneSummary.fromJson(Map<String, dynamic> json) =>
      _$CapstoneSummaryFromJson(json);
}
