// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'grade_view.freezed.dart';
part 'grade_view.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The mark range that maps to one letter grade for the class.
@freezed
@meta.immutable
sealed class GradeRange with _$GradeRange {
  const factory GradeRange({required String grade, required String range}) =
      _GradeRange;

  factory GradeRange.fromJson(Map<String, dynamic> json) =>
      _$GradeRangeFromJson(json);
}

/// Class-level statistics shown alongside a course's grade.
@freezed
@meta.immutable
sealed class GradeStatistics with _$GradeStatistics {
  const factory GradeStatistics({
    required String classStrength,
    required String gradingStrength,
    required String mean,
    required String sd,
    required List<GradeRange> gradeRanges,
  }) = _GradeStatistics;

  factory GradeStatistics.fromJson(Map<String, dynamic> json) =>
      _$GradeStatisticsFromJson(json);
}

/// One course row from the grade view for a semester.
@freezed
@meta.immutable
sealed class GradeViewCourse with _$GradeViewCourse {
  const factory GradeViewCourse({
    required String serialNumber,
    required String courseCode,
    required String courseTitle,
    required String courseType,
    required String gradingType,
    required String grandTotal,
    required String grade,
    required String courseId,
  }) = _GradeViewCourse;

  factory GradeViewCourse.fromJson(Map<String, dynamic> json) =>
      _$GradeViewCourseFromJson(json);
}

/// The expanded detail for a single course in the grade view.
@freezed
@meta.immutable
sealed class GradeViewDetail with _$GradeViewDetail {
  const factory GradeViewDetail({
    required String classNumber,
    required String courseType,
    required List<MarkComponent> marks,
    required String total,
    required GradeStatistics statistics,
  }) = _GradeViewDetail;

  factory GradeViewDetail.fromJson(Map<String, dynamic> json) =>
      _$GradeViewDetailFromJson(json);
}

/// One assessment component of a course (CAT1, FAT, a quiz, ...).
@freezed
@meta.immutable
sealed class MarkComponent with _$MarkComponent {
  const factory MarkComponent({
    required String serialNumber,
    required String markTitle,
    required String maxMark,
    required String weightage,
    required String status,
    required String scoredMark,
    required String weightageMark,
  }) = _MarkComponent;

  factory MarkComponent.fromJson(Map<String, dynamic> json) =>
      _$MarkComponentFromJson(json);
}
