// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';
import '../types/academic_calendar.dart';

// These functions are ignored because they are not marked as `pub`: `cal_date_regex`, `clean`, `month_number`, `parse_events`

/// Reads the class group options.
///
/// Class groups depend on the semester, so VTOP returns this `select` from
/// `getDateForSemesterPreview` once a semester is chosen rather than rendering
/// it up front.
///
/// # Examples
///
/// ```
/// let html = r#"
/// <select name="classGroupId" id="classGroupId">
///   <option value="COMB" selected="selected">All Class Group (Combined)</option>
///   <option value="ALL">General (Semester)</option>
/// </select>
/// "#.to_string();
///
/// let groups = lib_vtop::api::vtop::parser::calendar_parser::parse_class_groups(html);
///
/// assert_eq!(groups.len(), 2);
/// assert_eq!(groups[0].id, "COMB");
/// assert_eq!(groups[0].name, "All Class Group (Combined)");
/// ```
Future<List<ClassGroup>> parseClassGroups({required String html}) => RustLib
    .instance
    .api
    .crateApiVtopParserCalendarParserParseClassGroups(html: html);

/// Reads the month buttons for a semester.
///
/// Each button is an anchor whose `onclick` carries the `calDate` that
/// `processViewCalendar` expects. The label ("AUG-2026") and that value
/// ("01-AUG-2026") differ, so both are kept.
///
/// # Examples
///
/// ```
/// let html = r#"
/// <a onclick="javascript:processViewCalendar('01-AUG-2026');">AUG-2026</a>
/// <a onclick="javascript:processViewCalendar('01-SEP-2026');">SEP-2026</a>
/// "#.to_string();
///
/// let months = lib_vtop::api::vtop::parser::calendar_parser::parse_calendar_months(html);
///
/// assert_eq!(months.len(), 2);
/// assert_eq!(months[0].label, "AUG-2026");
/// assert_eq!(months[0].cal_date, "01-AUG-2026");
/// ```
Future<List<CalendarMonthRef>> parseCalendarMonths({required String html}) =>
    RustLib.instance.api.crateApiVtopParserCalendarParserParseCalendarMonths(
      html: html,
    );

/// Parses one month's grid into dated days.
///
/// VTOP lays a month out as a Sunday-to-Saturday week grid padded with blank
/// cells. The grid is a display concern, so this returns a flat, date-ordered
/// list instead: the weekday comes from the column each day sits in, and the
/// month and year from `cal_date`.
///
/// Returns an empty list when `cal_date` is not a month VTOP could have sent.
///
/// # Examples
///
/// ```
/// let html = r#"
/// <table class="table calendar-table">
///   <tr><th>Sunday</th><th>Monday</th></tr>
///   <tr>
///     <td><span></span></td>
///     <td><span>3</span><span>Instructional Day - General (Semester)</span><span>(WorkingDay)</span></td>
///   </tr>
/// </table>
/// "#.to_string();
///
/// let days = lib_vtop::api::vtop::parser::calendar_parser::parse_calendar_month(
///     html,
///     "01-AUG-2026".to_string(),
/// );
///
/// assert_eq!(days.len(), 1);
/// assert_eq!(days[0].date, "2026-08-03");
/// assert_eq!(days[0].weekday, "Monday");
/// assert_eq!(days[0].events[0].label, "WorkingDay");
/// ```
Future<List<CalendarDay>> parseCalendarMonth({
  required String html,
  required String calDate,
}) => RustLib.instance.api.crateApiVtopParserCalendarParserParseCalendarMonth(
  html: html,
  calDate: calDate,
);
