// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';
import '../types/capstone_attendance.dart';

// These functions are ignored because they are not marked as `pub`: `at`, `cells`, `clean`, `header_index`, `parse_info`, `parse_punches`, `parse_summary`, `value`

/// Parses the capstone/SDP attendance fragment returned by `processSdpAttendance`.
///
/// The response is a modal fragment holding three tables: the registration
/// info, the attendance tally, and a day-by-day punch calendar.
///
/// Returns `None` when the response carries no summary — which is what a
/// student with no capstone registration gets.
///
/// # Examples
///
/// ```
/// let html = r#"
/// <table class="table table-bordered">
///   <tr><th>Title</th><td>Capstone</td></tr>
///   <tr><th>Date of Registration</th><td>2026-07-06 00:00:00.0</td></tr>
/// </table>
/// <table class="table table-bordered text-center">
///   <tr><th>Present</th><th>On Duty (OD)</th><th>Absent</th><th>Percentage</th></tr>
///   <tr><td>14</td><td>4</td><td>12</td><td>60%</td></tr>
/// </table>
/// <table id="sdpCalendarTable">
///   <tr><th>Sl.No.</th><th>Date</th><th>Day</th><th>Day Type</th><th>Status</th><th>Punch Time</th></tr>
///   <tr><td>1</td><td>17-07-2026</td><td>FRIDAY</td><td>Instructional</td><td>Absent</td><td>-</td></tr>
/// </table>
/// "#.to_string();
///
/// let attendance =
///     lib_vtop::api::vtop::parser::capstone_attendance_parser::parse_capstone_attendance(html)
///         .expect("summary table present");
///
/// assert_eq!(attendance.info.title, "Capstone");
/// // The percent sign is stripped so the value parses as a number.
/// assert_eq!(attendance.summary.percentage, "60");
/// assert_eq!(attendance.punches.len(), 1);
/// // A dash means "nothing here" and is normalised to empty.
/// assert_eq!(attendance.punches[0].punch_time, "");
/// ```
Future<CapstoneAttendance?> parseCapstoneAttendance({required String html}) =>
    RustLib.instance.api
        .crateApiVtopParserCapstoneAttendanceParserParseCapstoneAttendance(
          html: html,
        );
