// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';
import '../types/grade_view.dart';

// These functions are ignored because they are not marked as `pub`: `clean`, `find_leaf_table`, `is_numeric`, `parse_statistics`

/// Parses the per-course grade list from a `doStudentGradeView` response.
///
/// # Examples
///
/// ```
/// let html = r#"
/// <table class="table table-hover table-bordered">
///   <tr><th>Sl.No.</th><th>Course Code</th><th>Course Title</th><th>Course Type</th>
///       <th>Grading Type</th><th>Grand Total</th><th>Grade</th><th>View Mark</th></tr>
///   <tr>
///     <td>1</td><td>CSE1008</td><td>Theory of Computation</td><td>Theory Only</td>
///     <td>RG</td><td>63</td><td>B</td>
///     <td><button onclick="javascript:getGradeViewDetails('AM_CSE1008_00200');">+</button></td>
///   </tr>
/// </table>
/// "#.to_string();
/// let courses = lib_vtop::api::vtop::parser::grade_view_parser::parse_grade_view(html);
/// assert_eq!(courses.len(), 1);
/// assert_eq!(courses[0].course_code, "CSE1008");
/// assert_eq!(courses[0].grade, "B");
/// assert_eq!(courses[0].course_id, "AM_CSE1008_00200");
/// ```
Future<List<GradeViewCourse>> parseGradeView({required String html}) => RustLib
    .instance
    .api
    .crateApiVtopParserGradeViewParserParseGradeView(html: html);

/// Parses the mark breakdown and class statistics from a `getGradeViewDetails`
/// response.
Future<GradeViewDetail> parseGradeViewDetail({required String html}) => RustLib
    .instance
    .api
    .crateApiVtopParserGradeViewParserParseGradeViewDetail(html: html);
