// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';
import '../types/paid_payment_receipt.dart';

// These functions are ignored because they are not marked as `pub`: `cell_text`, `extract_receipt_no`

/// Parses an HTML string to extract paid payment receipts from the receipts table.
///
/// Columns are located by their **header label** rather than a fixed position,
/// because VTOP has reordered and inserted columns in this table over time
/// (invoice number, fee group and fee subgroup now sit between the receipt
/// number and the amount). Positional fallbacks keep it working if the headers
/// ever change again.
///
/// The receipt number needed for the duplicate-receipt download lives in the
/// row's view button, which is located by its `doDuplicateReceipt(...)` handler
/// rather than a fixed cell. Rows without such a button (totals or empty-state
/// rows) are skipped rather than treated as receipts.
///
/// # Returns
/// A vector of `PaidPaymentReceipt` structs, one per receipt row.
///
/// # Examples
///
/// ```
/// let html = r#"
/// <table class="table table-bordered">
///   <tr>
///     <th>RECEIPT NUMBER</th><th>DATE</th><th>INVOICE NUMBER</th>
///     <th>FEE GROUP</th><th>FEE SUBGROUP</th><th>AMOUNT</th>
///     <th>CAMPUS CODE</th><th>VIEW</th>
///   </tr>
///   <tr>
///     <td>78323</td><td>08-JUL-2026</td><td>AM2600123276</td>
///     <td>HOSTEL FEE</td><td>Hostelfee</td><td>199300.0</td><td>AMR</td>
///     <td><button onclick="javascript:doDuplicateReceipt('78323/27/AMR');"></button></td>
///   </tr>
/// </table>
/// "#.to_string();
/// let receipts = lib_vtop::api::vtop::parser::payment_receipts_parser::parse_payment_receipts(html);
/// assert_eq!(receipts.len(), 1);
/// assert_eq!(receipts[0].receipt_number, "78323");
/// assert_eq!(receipts[0].amount, "199300.0");
/// assert_eq!(receipts[0].campus_code, "AMR");
/// assert_eq!(receipts[0].receipt_no, "78323/27/AMR");
/// ```
Future<List<PaidPaymentReceipt>> parsePaymentReceipts({required String html}) =>
    RustLib.instance.api
        .crateApiVtopParserPaymentReceiptsParserParsePaymentReceipts(
          html: html,
        );
